name: Link PR to Issue from Branch

on:
  pull_request:
    types: [opened]

jobs:
  link-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Extract issue number from branch
        id: extract
        run: |
          BRANCH="${{ github.head_ref }}"
          ISSUE=$(echo "$BRANCH" | grep -oE 'MP-[0-9]+' | grep -oE '[0-9]+')
          echo "ISSUE: $ISSUE"
        #   echo "issue=$ISSUE" >> $GITHUB_OUTPUT